project_id = "wanvrxtpqvxvczuzqhui"

[functions.send-invitation-email]
verify_jwt = true

[functions.send-payment-reminder]
verify_jwt = true

[functions.send-notifications]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.create-payment-link]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
